### ISSUE TITLE
Run the Diff Checker script on Schedules B, C, C1, C2, D, and E

### ISSUE THREAD

**Issue by Elaine-Krauss-TCG** [fecgov/fecfile-validate#266] opened 2023-08-31 17:03 UTC
Run the spec diff script (updating it where necessary) to find any discrepancies between the spreadsheets and the JSON schema files. Proceed to make corrections so that the diff script runs without reporting any errors.

- [ ] Schedule B
- [ ] Schedule C
- [ ] Schedule C1
- [ ] Schedule C2
- [ ] Schedule D
- [ ] Schedule E

### QA Notes:

Changes will likely be made to different JSON schema files which will result in changed behavior on the web app.  The dev handling this ticket will provide patch notes summarizing which schemas in which schedules were changed and what in them was fixed.  (See QA notes from Validate ticket #181 for example)

**Comment by mjtravers** [comment] 2024-02-21 18:11
Duplicate of #291. Closing ticket.

**Closed by mjtravers** 2024-02-21 18:11 UTC
Labels: technical debt
