### ISSUE TITLE
Spec Verification Script Maintenance

### ISSUE THREAD

**Issue by Elaine-Krauss-TCG** [fecgov/fecfile-validate#284] opened 2023-10-30 17:00 UTC
### Acceptance Criteria

Working with the Spec Verification script, ensure that the JSON schema files match the Spec Update excel sheets.  Running the script with each of the five Spec Update .xlsx files should result in zero errors.  This will likely require a combination of updates to the spec verification script, the json schema files, and possibly (with assistance from the BA's) the excel sheets.

Additionally, with each Spec Update excel file, there may be sheets that can't be matched to a JSON schema file.  This is expected for sheets that haven't been implemented yet, but these warnings should be investigated to make sure that there isn't a mismatch in naming.  The Spec Verification script looks for a JSON schema file with a filename that matches Cell A2 on each sheet, such as in the example below:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUNEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--deb5ff2ae29d1be730ab64afb2264fec5f1cb54d/image.png)

### DEV Notes

From the root fecfile-validate directory, run `python spec_verification [.xlsx file]` to check for errors.  This needs to be run separately with each of the five spec update sheets listed below.

#### Schedule A
[Sch A file](https://docs.google.com/spreadsheets/d/1SRS_hfYEHQl13aoC-z1xpxubfbKKNMSr/edit#gid=1335034634)
**Current Status:** 57 errors between 49 sheets.  1 sheet that can't be matched to a JSON schema file.

#### Schedule B
[Sch B file](https://docs.google.com/spreadsheets/d/1AmetsmSlI_UAJLeL715KWYJnyN09AsR-6wgXud3ldWs/edit#gid=1961093545)
**Current Status:** 33 errors between 11 sheets.  1 sheet that can't be matched to a JSON schema file.

#### Schedule C (Not verified before)
[Sch C file](https://docs.google.com/spreadsheets/d/1H1zZmpkhUrKqe25OShtQrgbH1TrhIOSxvI1ZOM-Fw9Y/edit#gid=388194567)
**Current Status:** 91 errors between 3 sheets.  3 sheets that can't be matched to JSON schema files.

#### Schedule D (Not verified before)
[Sch D file](https://docs.google.com/spreadsheets/d/1ykulNJdRI6J_PwVWk80QzBaopHZKVaEkgEjDo7RHeKQ/edit#gid=1956508297)
**Current Status:** 18 errors in 1 sheet.

#### Schedule E (Not verified before)
[Sch E file](https://docs.google.com/spreadsheets/d/15hqrgTeto1hp7i_9-jd719kTM9UNjN6qUPq-xOlJOco/edit#gid=1786117945)
**Current Status:** 99 errors in 3 sheets.  9 sheets that can't be matched to JSON schema files.

**Example of the script being run:**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlNEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b78df893e63736f4427736df88d84f02c11ab9b2/image.png)

### QA Notes

With changes to the JSON schema files, the behavior of individual transaction fields might be changed, depending on the errors being fixed in this ticket.  If the dev working this ticket changes the minimum/maximum length, requirement, regex pattern, etc. of a field, they should note the transaction, field, and change in a comment.

**Comment by mjtravers** [comment] 2023-11-28 20:50
This ticket is a duplicate of https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/gh/fecgov/fecfile-validate/291

Closing

**Closed by mjtravers** 2023-11-28 20:50 UTC
